name: CI model to dockerhub

# Trigger
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Actions
jobs:
  retraining_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest
    env:
      repo_token: ${{ secrets.GITHUBTOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run:
          pip3 install -r requirements.txt

      - name: Execute the training model
        run: |
          python3 retraining.py

      - name: Generating report
        run: |
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data visualization" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          cml-send-comment report.md

  build_docker_image:
    needs: retraining_model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t nathanghenassia/heart-attack-prediction-model:v1 .

      - name: Docker push dockerhub
        run: docker push nathanghenassia/heart-attack-prediction-model:v1

      - name: Login en Docker Hub to deploy en EC2
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
            if docker ps --all | grep -q heart; then
              docker stop heart
              docker rm heart
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/heart-attack-prediction-model:v1
            docker run -d --name heart -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/heart-attack-prediction-model:v1